### ISSUE TITLE
Explain how to read from variable

### ISSUE THREAD

**Issue by tupaschoal** [maxheld83/pandoc#14]
I am trying to feed a list of files to pandoc, which I have stored in my own file, per se, let's call it "file_list". I tried all alternatives below, to no avail. Note that I am not including the other parameters to make it simpler

1.
```
 run: INPUT_FILES=$(cat util/pdf_file_list.md)
 args: ${INPUT_FILES}
```

2.
```
 run: cat input_list | input_file.txt
 args: `cat input_file.txt`
```

**Comment by maxheld83** [comment]
Notice that `run:  ` runs on the *host* environment, whereas the `args` passed to pandoc are evaluated inside the container that's driving the pandoc action.

I think the problem here is that environment variables do not survive from step to step by default, or at least they don't make it into the action containers from the host environment.
To set an environment variable with the host environment, use something like `echo "::set-env name=action_state::yellow"`, documented [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions).

I think in addition, you'd then have to expose the environment variable to the pandoc action or container via [`jobs.<jobs_id>.steps.with`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepswith).

Some something like this should do the trick (haven't tested it):

```
jobs:
  my_first_job:
    steps:
      - run: `echo "::set-env name=INPUT_FILES::$(cat util/pdf_file_list.md)"
      - uses: docker://pandoc/core:2.9
        with:
          INPUT_FILES: ${{ INPUT_FILES }}
          args: "cat INPUT_FILES | input_file.txt"
```

Hope this helps.
